name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature you'd like in HiFidelity
      placeholder: "I'd love to see a dark theme option for the player controls"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      description: Tell us how this would help you
      placeholder: "I often listen to music at night and the bright interface strains my eyes"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: What part of the app is this about?
      options:
        - "Playing music"
        - "Organizing music"
        - "How it looks"
        - "Sound quality / Effects"
        - "Playlists"
        - "Search"
        - "New file format"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How much would you use this?
      options:
        - "Every day - Can't imagine using the app without it"
        - "Often - Would make things much easier"
        - "Sometimes - Would be nice to have"
        - "Rarely - Just a thought"
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Seen this in other apps?
      description: Optional - Have you seen other music players do something similar?
      placeholder: "Spotify has a dark mode that looks great"

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Optional - Any other details or ideas?
      placeholder: "Screenshots, mockups, or additional thoughts..."

